# the name of this file does not matter, we check all files in .github/workflows



---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 #docker and docker compose already installed on this image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1  # you can existing action for particular task
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout  
        uses: actions/checkout@v2  #provided by github for checking out the code
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
      